### ISSUE TITLE
Are there any references about the SHG code?

### ISSUE THREAD

**Issue by DreamingWeavers** [austinb3-optics-projects/Lab_11_second_harmonic_generation#1]
The simulation code of SHG is well written and detailed, but I cannot understand some of the formulas. Are there any references?

**Comment by austinb3-optics-projects** [comment]
Sure. I just added the lab the document the code is based on.

**Comment by austinb3-optics-projects** [comment]
I added the lab documents to my other repositories too in the case that you find yourself there as well.
